// AUTO-GENERATED by scripts/gen-solver-tables.cjs. Do not edit by hand.
//
// Byte layout of public/solver-tables.v1.bin — see that script
// for why this data is a fetched static asset rather than embedded in a
// JS module.

export const SOLVER_TABLES_URL = "/solver-tables.v1.bin";

export interface MoveTableEntry {
  name: string;
  rows: number;
  cols: number;
  byteOffset: number;
  byteLength: number;
}

export interface PruningTableEntry {
  name: string;
  length: number;
  byteOffset: number;
  byteLength: number;
}

export const MOVE_TABLE_MANIFEST: readonly MoveTableEntry[] = [
  { name: "twist", rows: 2187, cols: 18, byteOffset: 0, byteLength: 78732 },
  { name: "flip", rows: 2048, cols: 18, byteOffset: 78732, byteLength: 73728 },
  { name: "FRtoBR", rows: 11880, cols: 18, byteOffset: 152460, byteLength: 427680 },
  { name: "URFtoDLF", rows: 20160, cols: 18, byteOffset: 580140, byteLength: 725760 },
  { name: "URtoDF", rows: 20160, cols: 18, byteOffset: 1305900, byteLength: 725760 },
  { name: "URtoUL", rows: 1320, cols: 18, byteOffset: 2031660, byteLength: 47520 },
  { name: "UBtoDF", rows: 1320, cols: 18, byteOffset: 2079180, byteLength: 47520 },
  { name: "mergeURtoDF", rows: 336, cols: 336, byteOffset: 2126700, byteLength: 225792 },
];

export const PRUNING_TABLE_MANIFEST: readonly PruningTableEntry[] = [
  { name: "sliceTwist", length: 135321, byteOffset: 2352492, byteLength: 541284 },
  { name: "sliceFlip", length: 126720, byteOffset: 2893776, byteLength: 506880 },
  { name: "sliceURFtoDLFParity", length: 120960, byteOffset: 3400656, byteLength: 483840 },
  { name: "sliceURtoDFParity", length: 120960, byteOffset: 3884496, byteLength: 483840 },
];
