// AUTO-GENERATED by scripts/gen-ll-cases.cjs. Do not edit by hand.
//
// The 21 permutation classes of the last layer. Unlike OLL, the standard
// names follow from each case's cycle structure, so each name is pinned to
// its permutation class and algorithms are filed under the case they
// actually solve. Written in the traditional last-layer-on-U frame.
import type { AlgCase } from "./types";

export const PLL_CASES: AlgCase[] = [
  { id: "pll-ua", name: "Ua Perm", group: "PLL", alg: "R U' R U R U R U' R' U' R2" },
  { id: "pll-ub", name: "Ub Perm", group: "PLL", alg: "R2 U R U R' U' R' U' R' U R'" },
  { id: "pll-h", name: "H Perm", group: "PLL", alg: "M2 U M2 U2 M2 U M2" },
  { id: "pll-z", name: "Z Perm", group: "PLL", alg: "M' U M2 U M2 U M' U2 M2" },
  { id: "pll-aa", name: "Aa Perm", group: "PLL", alg: "x R' U R' D2 R U' R' D2 R2 x'" },
  { id: "pll-ab", name: "Ab Perm", group: "PLL", alg: "x R2 D2 R U R' D2 R U' R x'" },
  { id: "pll-e", name: "E Perm", group: "PLL", alg: "x' R U' R' D R U R' D' R U R' D R U' R' D' x" },
  { id: "pll-t", name: "T Perm", group: "PLL", alg: "R U R' U' R' F R2 U' R' U' R U R' F'" },
  { id: "pll-f", name: "F Perm", group: "PLL", alg: "R' U' F' R U R' U' R' F R2 U' R' U' R U R' U R" },
  { id: "pll-ja", name: "Ja Perm", group: "PLL", alg: "R' U L' U2 R U' R' U2 R L" },
  { id: "pll-jb", name: "Jb Perm", group: "PLL", alg: "L U' R U2 L' U L U2 L' R'" },
  { id: "pll-ra", name: "Ra Perm", group: "PLL", alg: "L U2 L' U2 L F' L' U' L U L F L2" },
  { id: "pll-rb", name: "Rb Perm", group: "PLL", alg: "R' U2 R U2 R' F R U R' U' R' F' R2" },
  { id: "pll-v", name: "V Perm", group: "PLL", alg: "R' U R U' R' f' U' R U2 R' U' R U' R' f R" },
  { id: "pll-y", name: "Y Perm", group: "PLL", alg: "F R U' R' U' R U R' F' R U R' U' R' F R F'" },
  { id: "pll-na", name: "Na Perm", group: "PLL", alg: "L U' L' U L F U F' L' U' L F' L F L' U L'" },
  { id: "pll-nb", name: "Nb Perm", group: "PLL", alg: "R' U R U' R' F' U' F R U R' F R' F' R U' R" },
  { id: "pll-ga", name: "Ga Perm", group: "PLL", alg: "R2 U R' U R' U' R U' R2 D U' R' U R D'", shape: "G Perm" },
  { id: "pll-gb", name: "Gb Perm", group: "PLL", alg: "R' U' R U D' R2 U R' U R U' R U' R2 D", shape: "G Perm" },
  { id: "pll-gc", name: "Gc Perm", group: "PLL", alg: "R2 U' R U' R U R' U R2 D' U R U' R' D", shape: "G Perm" },
  { id: "pll-gd", name: "Gd Perm", group: "PLL", alg: "R U R' U' D R2 U' R U' R' U R' U R2 D'", shape: "G Perm" },
];
