/**
 * Every static page in the app. The service worker saves each one (and the scripts and styles it
 * uses) once the app has loaded online, so any of them opens with no connection. A test keeps this
 * in step with src/app — add a page there and it fails until it's listed here.
 *
 * Not listed: /solve/[id] (a shared solve, which lives on the server) and /offline itself, which
 * the worker keeps separately.
 */
export const OFFLINE_ROUTES = [
  "/",
  "/algid",
  "/algspeed",
  "/ar",
  "/archetypes",
  "/auf",
  "/autopsy",
  "/bld",
  "/blindcross",
  "/blindspots",
  "/bottleneck",
  "/cadence",
  "/cases",
  "/coach",
  "/coldstart",
  "/comp",
  "/consistency",
  "/crosscolor",
  "/duel",
  "/echo",
  "/economy",
  "/eventmix",
  "/experiments",
  "/f2lcases",
  "/goal",
  "/golf",
  "/gym",
  "/inspection",
  "/journey",
  "/lab",
  "/lookahead",
  "/luck",
  "/maze",
  "/mistakes",
  "/momentum",
  "/multislot",
  "/myalgs",
  "/pacer",
  "/play",
  "/portraits",
  "/progress",
  "/quests",
  "/reel",
  "/rematch",
  "/rhythm",
  "/rotations",
  "/satnav",
  "/sob",
  "/solves",
  "/spin",
  "/stalls",
  "/stamina",
  "/tempo",
  "/tilt",
  "/timemachine",
  "/twistris",
  "/vault",
  "/wake",
  "/wrapped",
  "/xcross",
  "/xray",
] as const;

/** Files outside the page bundles that a page can't work without. */
export const OFFLINE_EXTRAS = ["/offline", "/solver-tables.v1.bin", "/icon.svg", "/manifest.webmanifest"] as const;
